server:
  port: 8089

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookMistakes?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
mybatis:
  mapper-locations: classpath:mapper/*.xml